server {
    listen 80;

    # 1. Sirve el Frontend (index.html e index.js)
    location / {
        root /usr/share/nginx/html;
        index index.html;
    }

    # 2. Proxy hacia el Backend (Capa Privada)
    location /api/v1/ {
        proxy_pass http://10.0.129.39:80/api/v1/; #<- esta ip debe cambiar por tu ip privada
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}